# Generated by Django 5.0.1 on 2024-01-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
